name: "Ruby on Rails CI"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: db
          TEST_DB_USERNAME: postgres
          TEST_DB_PASSWORD: postgres
        ports:
          - 5432:5432
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      - name: Build Rails container
        run: docker build -f .github/workflows/Dockerfile . -t choremgr_ruby
      - name: Create database and migrate
        run: |
          docker-compose run --rm web rails db:drop &&
          docker-compose run --rm web rails db:create &&
          docker-compose run --rm web rails db:migrate
        env:
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          DATABASE_URL: "postgresql://postgres@localhost/choremgr_rails"
      - name: Run tests
        run: docker-compose run --rm web rspec
        env:
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
          DATABASE_URL: "postgresql://postgres@localhost/choremgr_rails"
